## Word Embedding

In [ ]:
# Import library
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# List of sentences
sentences = [
  "The glass of milk",
  "the glass of juice",
  "The cup of tea",
  "I am a good boy",
  "I am a good developer",
  "understande the meaning of the words",
  "Your videos are good",
]

In [5]:
# Define vocabulary size
vocab_size = 10000

# One hot representation for every words
one_hot_representation = [one_hot(words, vocab_size) for words in sentences]
one_hot_representation

[[6812, 7625, 6572, 1486],
 [6812, 7625, 6572, 5168],
 [6812, 8503, 6572, 2359],
 [9864, 2136, 4985, 9254, 7714],
 [9864, 2136, 4985, 9254, 8325],
 [6276, 6812, 132, 6572, 6812, 5520],
 [2036, 2722, 9139, 9254]]

In [7]:
# Word embedding representation
import numpy as np

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
sentence_length = 8
embedded_docs = pad_sequences(one_hot_representation, padding="pre", maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0    0 6812 7625 6572 1486]
 [   0    0    0    0 6812 7625 6572 5168]
 [   0    0    0    0 6812 8503 6572 2359]
 [   0    0    0 9864 2136 4985 9254 7714]
 [   0    0    0 9864 2136 4985 9254 8325]
 [   0    0 6276 6812  132 6572 6812 5520]
 [   0    0    0    0 2036 2722 9139 9254]]


In [9]:
# Feature Representation
dim = 10

# Create the model
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sentence_length))
model.compile(optimizer="adam", loss="mse")
model.summary()

c:\MySkill\Data Science\Projects\nlp-dl-projects\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Predict the embedding
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step


array([[[-2.38830969e-03, -2.22583171e-02, -4.11004908e-02,
          1.81509294e-02, -3.52668650e-02,  3.32099833e-02,
          2.52459161e-02, -3.63948457e-02,  6.67641312e-03,
         -3.40905190e-02],
        [-2.38830969e-03, -2.22583171e-02, -4.11004908e-02,
          1.81509294e-02, -3.52668650e-02,  3.32099833e-02,
          2.52459161e-02, -3.63948457e-02,  6.67641312e-03,
         -3.40905190e-02],
        [-2.38830969e-03, -2.22583171e-02, -4.11004908e-02,
          1.81509294e-02, -3.52668650e-02,  3.32099833e-02,
          2.52459161e-02, -3.63948457e-02,  6.67641312e-03,
         -3.40905190e-02],
        [-2.38830969e-03, -2.22583171e-02, -4.11004908e-02,
          1.81509294e-02, -3.52668650e-02,  3.32099833e-02,
          2.52459161e-02, -3.63948457e-02,  6.67641312e-03,
         -3.40905190e-02],
        [ 3.33881862e-02,  1.11368410e-02,  1.47405975e-02,
          3.34346294e-03,  3.08276676e-02, -1.71473026e-02,
         -4.49168086e-02, -1.29369386e-02, -1.181914